FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["Code/CodeQL.Api/CodeQL.Api.csproj", "Code/CodeQL.Api/"]
COPY ["Code/CodeQL.Business/CodeQL.Business.csproj", "Code/CodeQL.Business/"]
COPY ["Code/CodeQL.Data/CodeQL.Data.csproj", "Code/CodeQL.Data/"]
COPY ["Code/CodeQL.Entities/CodeQL.Entities.csproj", "Code/CodeQL.Entities/"]
COPY ["Code/CodeQL.Test.Api/CodeQL.Test.Api.csproj", "Code/CodeQL.Test.Api/"]
COPY ["Code/CodeQL.Test.Business/CodeQL.Test.Business.csproj", "Code/CodeQL.Test.Business/"]
RUN dotnet restore "Code/CodeQL.Api/CodeQL.Api.csproj"
COPY . .
WORKDIR "/src/Code/CodeQL.Api"
RUN dotnet build "CodeQL.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CodeQL.Api.csproj" -c Release -o /app/publish

WORKDIR /src
RUN dotnet test --results-directory /testresults --logger "trx;LogFileName=testresults.Api.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=/testresults/coverage/ /p:MergeWith=/testresults/coverage/coverage.json "Code/CodeQL.Test.Api/CodeQL.Test.Api.csproj"
RUN dotnet test --results-directory /testresults --logger "trx;LogFileName=testresults.Api.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=/testresults/coverage/ /p:MergeWith=/testresults/coverage/coverage.json "Code/CodeQL.Test.Business/CodeQL.Test.Business.csproj"
